### ISSUE TITLE
How to exclude folder ?

### ISSUE THREAD

**Issue by iSynth** [jakobwesthoff/phuml#5]
Hello!

Nice work!
Tell me please, how can I exclude folder(s) from project path? For example, I have a vendor folder with composer controlled sources and I want to exclude this folder from UML generation.

**Comment by jakobwesthoff** [comment]
Currently this is not implemented. Furthermore as I discontinued the Project quite a while ago, there are currently no plans to integrate this Feature. However PRs or take over requests of maintenance/ownership are of course always welcome.
